### ISSUE TITLE
[Quilt 1.19.2] game crashes whenever i try placing framed panels on top of things

### ISSUE THREAD

**Issue by glittermutt** [LoremVIpsum/OpenSimpleFrames#20]
[crash-2023-09-29_14.43.36-client.txt](https://github.com/LoremVIpsum/OpenSimpleFrames/files/12763313/crash-2023-09-29_14.43.36-client.txt)
yeah thats about it, crash report attached

**Comment by LoremVIpsum** [comment]
Will check this soon, however I'm not entirely sure this mod will work with quilt as it wasn't built with it in mind, so thwre may be discrepancies between the toolchains

**Comment by glittermutt** [comment]
thank you for checking still! and i did try fabric, ran into the same issue

**Comment by Cha0sBEpic** [comment]
Im Having this same issue only int 1.20.1 Fabric. I have discovered that it only happens when im looking down at my feet while i try to place it on the edge.
[crash-2023-10-28_08.45.32-client.txt](https://github.com/LoremVIpsum/OpenSimpleFrames/files/13195983/crash-2023-10-28_08.45.32-client.txt)

Just checked and it happens also when you try to place it while looking up as well

**Comment by GameBurrow** [comment]
Can confirm this happening Fabric 1.20.1 also - if look straight at block, won't crash, if I look up or down, it crashes.

[crash-2023-11-13_12.32.46-client.txt](https://github.com/LoremVIpsum/OpenSimpleFrames/files/13333889/crash-2023-11-13_12.32.46-client.txt)
