### ISSUE TITLE
Updating to 1.21

### ISSUE THREAD

**Issue by Pokerfaceuhd** [LoremVIpsum/OpenSimpleFrames#40]
I have been working on porting this mod to 1.21, there is only one issue left.

In BakedQuadFactoryMixin it needs to filter out some stuff with modelId.getPath().equals(base) in the capture method but modelId (which is of type Identifier) no longer gets input into the bake method in BakedQuadFactory. Ive tried using the ModelBakeSettings and casting those to ModelVariants which have the Path but that doesnt seem to work lead to the same results. 

Without it all the models try to render on top of each other for every simple frames block. 

I would appreciate some help with this.

**Comment by LoremVIpsum** [comment]
So as you can probably see I haven't logged into this account for a while because of life and such, but thank you for attempting to port the mod! at some point I really want to rewrite a bunch of the internals to fix a bunch of the errors but I haven't had time yet - there is the potentially that the method you are using or think your using is now called something else entirely if you look through that class, and then it might have the identifier as inputs, otherwise its probably codecs and records which i do not know so much about

**Comment by CubE135** [comment]
> I have been working on porting this mod to 1.21, there is only one issue left.
> 
> In BakedQuadFactoryMixin it needs to filter out some stuff with modelId.getPath().equals(base) in the capture method but modelId (which is of type Identifier) no longer gets input into the bake method in BakedQuadFactory. Ive tried using the ModelBakeSettings and casting those to ModelVariants which have the Path but that doesnt seem to work lead to the same results.
> 
> Without it all the models try to render on top of each other for every simple frames block.
> 
> I would appreciate some help with this.

Have you had success completing the port to 1.21?
I have been looking for a 1.21 version of some sort of framed blocks for a while :/

**Comment by Pokerfaceuhd** [comment]
Sadly I dropped this project cause it was frustrating me, Im not even sure if I can get the files again of the half broken version, sorry.
